Include caselist in run_gpu_mask.lsf script for consistency
pnlbwh/luigi-pnlpipe pull request #58
Opened 2022-10-26 13:33 UTC by tashrifbillah

Credited to @goofballkim

2022-10-26 17:07 UTC, GoofballKim approved these changes

2022-10-26 17:31 UTC, GoofballKim requested changes

2022-10-26 17:31 UTC, GoofballKim commented on workflows/run_gpu_mask.lsf
> +# a single caseid or a text file with list of cases
It may be useful to include analogous code for a sessionlist.

2022-10-26 17:31 UTC, GoofballKim commented on workflows/run_gpu_mask.lsf
> +# a single caseid or a text file with list of cases
It may be useful to include the following comment: "Use of caselist recommended if submitting job, but not if running directly on terminal."

2022-10-28 19:20 UTC, merged

2022-10-28 19:20 UTC, tashrifbillah commented
Thank you, Nick.